export const buildUser = (overrides = {}) => ({
  login: 'octocat',
  name: 'The Octocat',
  avatar_url: 'https://avatars.example.com/octocat.png?v=1',
  html_url: 'https://github.com/octocat',
  bio: 'GitHub mascot',
  email: 'octocat@github.com',
  location: 'San Francisco',
  blog: 'https://github.blog',
  followers: 10000,
  following: 9,
  public_repos: 8,
  ...overrides,
});

export const buildRepo = (overrides = {}) => ({
  id: 1,
  name: 'hello-world',
  full_name: 'octocat/hello-world',
  description: 'My first repository',
  html_url: 'https://github.com/octocat/hello-world',
  homepage: null,
  language: 'JavaScript',
  stargazers_count: 100,
  forks_count: 25,
  watchers_count: 100,
  open_issues_count: 3,
  updated_at: '2024-06-01T00:00:00Z',
  created_at: '2020-01-01T00:00:00Z',
  pushed_at: '2024-06-01T00:00:00Z',
  fork: false,
  private: false,
  archived: false,
  topics: [],
  license: null,
  owner: {
    login: 'octocat',
    avatar_url: 'https://avatars.example.com/octocat.png?v=1',
  },
  ...overrides,
});
